import { index, layout, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  route("sign-in", "routes/sign-in.tsx"),
  route("sign-in/reset", "routes/sign-in.reset.tsx"),
  route("enroll", "routes/enroll.tsx"),
  route("sign-out", "routes/sign-out.tsx"),
  route("setup", "routes/setup.tsx"),
  route("resources/break-glass", "routes/resources.break-glass.tsx"),
  route("resources/diagnostics", "routes/resources.diagnostics.tsx"),
  route("resources/display", "routes/resources.display.tsx"),
  route("resources/notifications", "routes/resources.notifications.tsx"),
  route("resources/step-up", "routes/resources.step-up.tsx"),
  route("healthz", "routes/healthz.tsx"),
  layout("routes/frame.tsx", [
    index("routes/home.tsx"),
    route("users", "routes/users.tsx"),
    route("users/new", "routes/users.new.tsx"),
    route("users/:id", "routes/users.$id.tsx"),
    route("users/:id/verify", "routes/users.$id.verify.tsx"),
    route("groups", "routes/groups.tsx"),
    route("groups/new", "routes/groups.new.tsx"),
    route("groups/:id", "routes/groups.$id.tsx"),
    route("types", "routes/types.tsx"),
    route("types/new", "routes/types.$id.tsx", { id: "routes/types.new" }),
    route("types/:id", "routes/types.$id.tsx"),
    route("policies", "routes/policies.tsx"),
    route("policies/new", "routes/policies.$id.tsx", { id: "routes/policies.new" }),
    route("policies/:id", "routes/policies.$id.tsx"),
    route("settings", "routes/settings.tsx"),
    route("targets", "routes/targets.tsx"),
    route("targets/new", "routes/targets.$id.tsx", { id: "routes/targets.new" }),
    route("targets/:id", "routes/targets.$id.tsx"),
    route("connections", "routes/connections.tsx"),
    route("service-accounts", "routes/service-accounts.tsx"),
    route("service-accounts/new", "routes/service-accounts.new.tsx"),
    route("service-accounts/:id", "routes/service-accounts.$id.tsx"),
    route("audit", "routes/audit.tsx"),
    route("audit/export", "routes/audit.export.tsx"),
    route("folders", "routes/folders.tsx"),
    route("folders/:id", "routes/folders.tsx", { id: "routes/folders.$id" }),
  ]),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
